build:Modelica:
  stage: build
  script:
    - build
  artifacts:
    paths:
    - Arduino-Modelica.zip
    expire_in: 1 week

test:Modelica:
  stage: test
  script: test
  dependencies:
    - build:Modelica
  artifacts:
    paths:
    - Temp/Arduino/*.png
    expire_in: 1 week
